# Generated by Django 3.1.3 on 2021-08-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20201128_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypicture',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
