# Generated by Django 3.1.3 on 2020-11-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20201128_1728'),
        ('framestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framestate',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.gallery'),
        ),
    ]
