# Generated by Django 3.1.3 on 2021-07-31 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framestate', '0002_framestate_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framestate',
            name='frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to=settings.AUTH_USER_MODEL),
        ),
    ]
