# Generated by Django 3.1.3 on 2020-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201107_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frame_location',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('P', 'Person'), ('F', 'Frame')], default='P', max_length=1),
        ),
    ]
