site_name: fspictureframe
site_description: A digital picture frame API
repo_url: https://github.com/finitesingularity/fs-picture-frame
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/finitesingularity">finitesingularity</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
